# syntax=docker/dockerfile:1
# ── LukitaPort ────────────────────────────────────────────────────────────────
# Build:   docker build -t lukitaport .
# Lite:    docker build --build-arg WITH_SCREENSHOTS=false -t lukitaport:lite .
#          (no Playwright/Chromium: ~1 GB smaller, screenshots disabled)
# Run:     see docker-compose.yml — LUKITA_API_TOKEN is mandatory in a container.

FROM python:3.12-slim

ARG WITH_SCREENSHOTS=true

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# nmap: service fingerprinting · iputils-ping: network discovery
RUN apt-get update \
    && apt-get install -y --no-install-recommends nmap iputils-ping ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Pinned, hash-checked dependencies (requirements.txt is generated by
# pip-compile from pyproject.toml).  `playwright install --with-deps` pulls
# exactly the system libraries Chromium needs.
COPY requirements.txt .
RUN pip install --require-hashes -r requirements.txt \
    && if [ "$WITH_SCREENSHOTS" = "true" ]; then \
           playwright install --with-deps chromium && rm -rf /var/lib/apt/lists/*; \
       else \
           pip uninstall -y playwright; \
       fi

RUN useradd --system --uid 10001 --home-dir /nonexistent --shell /usr/sbin/nologin lukita

# Application code only (see .dockerignore), owned by root: read-only for the app.
COPY *.py tech_signatures.json ./
COPY frontend/ ./frontend/

ENV HOME=/tmp \
    LUKITA_HOST=0.0.0.0 \
    LUKITA_PORT=8000

USER lukita
EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD ["python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/health', timeout=4)"]

# run.py refuses to listen on 0.0.0.0 unless LUKITA_API_TOKEN is set.
CMD ["python", "run.py"]
